---
creation_rules:
  - path_regex: talos/.*\.sops\.yaml$
    age: >-
      age1hm8fzvp84xsqwtwc2pjkssqe4us5tzq07fxfcu0spch37ad29auqnkygm5
  - path_regex: kubernetes/.*\.sops\.yaml$
    age: >-
      age1hm8fzvp84xsqwtwc2pjkssqe4us5tzq07fxfcu0spch37ad29auqnkygm5
