- name: Check if Incus is already initialized
  ansible.builtin.command:
    cmd: incus storage list --format csv
  register: storage_check
  changed_when: false
  failed_when: false

- name: Configure Incus with preseed
  become: true
  ansible.builtin.command:
    cmd: incus admin init --preseed
    stdin: "{{ lookup('template', 'preseed.yaml.j2') }}"
  when: storage_check.stdout == ""
  changed_when: storage_check.stdout == ""
