- name: Add Zabbly source
  ansible.builtin.import_tasks: repo_deb.yaml
  tags:
    - install

- name: Install Incus and prepare the host for setup
  ansible.builtin.import_tasks: install.yaml
  tags:
    - install

- name: Initialize Incus
  ansible.builtin.import_tasks: init.yaml
  tags:
    - init

- name: Prepare client for remote access
  ansible.builtin.import_tasks: client.yaml
  tags:
    - client
