# To create:
# 1. Visit: https://login.tailscale.com/admin/settings/oauth
# 2. Create OAuth Client with scope: Devices (Core: Read & Write)
# 3. Create operator-oauth Secret in network namespace:
#    kubectl create secret generic operator-oauth -n network \
#      --from-literal=client_id="<YOUR_CLIENT_ID>" \
#      --from-literal=client_secret="<YOUR_CLIENT_SECRET>"
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: network
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:SxmTSWd5bZO/9yIpTxRoUh4=,iv:erBGZGJj3AoY2hnVXDTUph9FHtMh0GGAtvA06vKKd/8=,tag:2syZZ2sos3iJq6JCBI8l3A==,type:str]
    client_secret: ENC[AES256_GCM,data:PKmsQEGc6Bx3ZnaBipzVdp9Xno/9mlB6Y5ZzzWNScVUQueOLhOmWnZfrzI9q1L1bR1rH9h6nhNCLY46HV6rN,iv:koO86s7sejtMKAlrlCTrme3vxbf7mvpMRG1IyaV3AE4=,tag:dR4c3Ov6A9EPplvCGcBD7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZW5GS0lPN1ZFdlI3bDQ5
            SXdoVElucnpLeXdqd3k3ZG04QlBFczlLM0VVCjloRHN3TDcvbTRvT1F6QU1rbWs0
            ZU9ZaEI0VEdieEw2NmNkUTBsTHhnaG8KLS0tIFhIRytmOHRTc1Rua1JRNjdtZnUy
            cmRhZWtET2Y4bWNjWjZiZ3VaY09SSUUKD/XeR/4BzYjXgu0149XYFmrudLGrBUM7
            OinXy6jNoPKwflSGOkPWG+dqhG2H5v7WgXkW8op+lUptwvkfnu6WLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hm8fzvp84xsqwtwc2pjkssqe4us5tzq07fxfcu0spch37ad29auqnkygm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-25T04:57:12Z"
    mac: ENC[AES256_GCM,data:o+8R82UdP/WAdxlT0Dc9nRrJD0LG2cDGPvLgRRpzY3YZ6PdgcLvFoOt+KtNwjuaGRa/tD/Aej3/au2IBLBQczpOYoLtVY8WGaPt7tsXr0EYrGrl5WRopX+hcRddaSDMhMqfu4GfbeZkiBBuUDPQEYvFGvO8DwCDB7GjLg9frVgM=,iv:NMkqb6P2IDHz6ssB+J2Yg/3M55WkX0TZD26dYigfJnY=,tag:EBqZqD4F8glueRFAlTJ7QA==,type:str]
    version: 3.13.3
