# Incus API
incus_https_address: "[::]:8443"

# Storage
incus_storage_pool_name: "default"
incus_storage_pool_driver: "zfs"  # dir, zfs, btrfs, lvm

# Network
incus_network_name: "br-in"
incus_network_ipv4_address: "auto"
incus_network_ipv6_address: "auto"

# Client config
incus_remote_name: "homelab"
incus_client_name: "incus-client"
incus_client_config_path: "~/.config/incus"
incus_server_cert_path: "/tmp/client.crt"
