# To create:
# 1. Update the admin_password with your desired Grafana admin password.
# 2. Encrypt using SOPS with age:
#    sops --encrypt grafana-admin-secret.sops.yaml.example > grafana-admin-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin_password: ENC[AES256_GCM,data:xAG9SjagxKy5,iv:vPp/33MWfo1p4ZgIte0bqkheCHyf/T9gjjEPxOzGlTs=,tag:eSkTPU+OOTZ6gN94gLFeZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OTBvZzcyMmQyUGJtR1p2
            Si90em1raWN6bVFxKzRyOWRwLzBxa2VtY0JZCkF1T2pRekdPeWowa1dPQ25weUtu
            TU9GRkZ0WWIxT2lFd0xTTk96QjVpUGMKLS0tIHVFeURNcm0wS2gzZ3hVOTJZQ1Yw
            MHJ6UkJ1UmVETmhEM2NBK1I1TWZpNm8K+TFl3ULHRofzqGrD/m89arGC2qYrsENq
            UiXFMOLUcmyU2BkcCZbDuW7ezWQaXURGhhmbeo8FrSleIewTQGHr3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hm8fzvp84xsqwtwc2pjkssqe4us5tzq07fxfcu0spch37ad29auqnkygm5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T02:04:44Z"
    mac: ENC[AES256_GCM,data:ek1BNABxFEulR/SYeyou/Np/vGN0DFE2704yocdgJ69jB+mxpVK7C8A1A18zsJoQTKX43a/DFBc3KbMHJhW6ORChR9u7ZcuF2yYbZFJ0iZn0ppGPkYfqNSZvZWl2f5J6QKtztAxQm4Fi53JtSynYWSXPbUy+P6kXAEmNwnJeW8s=,iv:cvYCQ7mb9f2odjVz3vTiHFViKgB4WYxuRVirN3nryDY=,tag:dR8/cZzjw0PlfrgQ+3mTAg==,type:str]
    version: 3.13.3
